# Generated by Django 5.0.3 on 2024-03-31 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_officehoursession_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officehoursession',
            name='id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, unique=True),
        ),
    ]
