# Generated by Django 4.2.11 on 2024-04-11 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_sessiontoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessiontoken',
            old_name='api_key',
            new_name='access_token',
        ),
        migrations.RenameField(
            model_name='sessiontoken',
            old_name='api_refresh_key',
            new_name='refresh_token',
        ),
        migrations.RenameField(
            model_name='sessiontoken',
            old_name='token',
            new_name='session_token',
        ),
    ]
