# Generated by Django 4.2.11 on 2024-04-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_api_key_sessiontoken_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='canvas_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
