# Generated by Django 4.2.11 on 2024-04-16 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_sessionquestion_sessionresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionquestion',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.professor'),
        ),
    ]
