# Generated by Django 4.2.11 on 2024-04-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_waitlist_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
