# Generated by Django 4.2.11 on 2024-04-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_sessionquestion_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
