# Generated by Django 4.2.11 on 2024-04-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_officehoursession_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
